packaging_format = 2
id = "solifloute"
name = "Solifloute"
description.en = "Isomorphic video and photo blurring system made by the French student union Solidaires Étudiant-e-s"
description.fr = "Système de floutage vidéo et photo isomorphe créé par le syndicat Solidaires Étudiant-e-s"

version = "2.0.0~ynh1"

maintainers = ["ebanDev"]


[upstream]
license = "AGPL-3.0"
code = "https://github.com/Solidaires-Etudiant-e-s/Solifloute"

[integration]
yunohost = ">= 11.1"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
disk = "100M"
ram.build = "1G"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Solidaires-Etudiant-e-s/solifloute/archive/refs/tags/v2.0.0.tar.gz"
    sha256 = "b4e632c5ffcfd968600b0d37f2d2d5970937408b0b8ae755d83261ec34d3c0d3"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"

    [resources.nodejs]
    version = "22"

    [resources.data_dir]

    [resources.apt]
    packages = ["ffmpeg"]
